name: Deploy to Live Channel

on:
  push:
    branches:
      - main

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn
      - name: Run Tests
        run: yarn test --ci
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BET_LOG_24881 }}
          channelId: live
          projectId: bet-log-24881
